<?php
return array (
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1220',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'wjm3u8' => 
  array (
    'status' => '1',
    'from' => 'wjm3u8',
    'show' => '无尽①',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1194',
    'tip' => '无需安装任何插件',
    'id' => 'wjm3u8',
  ),
  'hnm3u8' => 
  array (
    'status' => '1',
    'from' => 'hnm3u8',
    'show' => '红牛在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1193',
    'tip' => '无需安装任何插件',
    'id' => 'hnm3u8',
  ),
  'kkm3u8' => 
  array (
    'status' => '1',
    'from' => 'kkm3u8',
    'show' => 'KK在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1045',
    'tip' => '无需安装任何插件',
    'id' => 'kkm3u8',
  ),
  'bmm3u8' => 
  array (
    'status' => '1',
    'from' => 'bmm3u8',
    'show' => '博民资源①',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'bmm3u8',
  ),
  'slm3u8' => 
  array (
    'status' => '1',
    'from' => 'slm3u8',
    'show' => '森林资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'slm3u8',
  ),
);